name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install binutils-z80

    - name: Build
      run: make all
    
    - uses: actions/upload-artifact@v4
      with:
        name: rom.bin
        path: rom.bin

  release:
    name: Release
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: rom.bin
    - name: Test
      run: ls -l
